# Generated by Django 5.2 on 2025-05-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_core', '0002_alter_loanapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapplication',
            options={},
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='assets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='credit_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='total_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='collateral_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='duration',
            field=models.IntegerField(help_text='months'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='employment_type',
            field=models.CharField(choices=[('full-time', 'Full‑Time'), ('part-time', 'Part‑Time'), ('self-employed', 'Self‑Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
