# Generated by Django 5.2 on 2025-05-15 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('loan_core', '0003_alter_loanapplication_options_loanapplication_assets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('debt_to_income_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('banking_history', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
