# Generated by Django 5.2 on 2025-05-15 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_core', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
